### ISSUE TITLE
How to create a valid user pool

### ISSUE THREAD

**Issue by srebrny** [markgawler/phpbbCognitoAuth#2]
Hello, 

I want use this library, after some optimalization in composer.json it runs on phpbb 3.2.7. 

But they dont match any user from cognito. 

Maybe we should create some Wiki how to create a user pool for this project?

**Comment by markgawler** [comment]
Hi, Its not ready for production use at the moment, I'll push my latest changes which rework the phpBB ACP and add error handling. It will be possible to create the user pool from the phpBB ACP, the latest changes start this by configuring the App Client.

**Comment by srebrny** [comment]
Ok how can i run it to create valid pool, maybe you have some saved links for little help? 

After that I update docs in project

**Comment by markgawler** [comment]
I have updated the ACP to create a basic User Pool and Use Pool App Client. The Pool that is created is sufficient for phpBB users to be migrated to as they login and  once migrated the user is authenticated against the pool.

You will need de uninstall (and delete data) from an previous version of this extension be for installing this latest update. 

The password policies are partly hard coded, only the min length is copied from phpBB to the User Pool.

The Documentation for Creating User Pools manually is here.
https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools.html

Please remember this is all work in progress and not ready for  production use.
