### ISSUE TITLE
Attempting to enable the extension on phpBB3 returns error "A migration is invalid. An unknown migration tool type was encountered"

### ISSUE THREAD

**Issue by DevoKun** [markgawler/phpbbCognitoAuth#4]
* **PHP version**:  `7.4.3`
* **phpBB version**:  `3.3.5`

<img width="1269" alt="Screen Shot 2021-11-24 at 10 14 15 PM" src="https://user-images.githubusercontent.com/935976/143375722-3eae412b-9133-44d7-a953-bccec94653a5.png">

**Comment by markgawler** [comment]
I have not looked at this extension for two years, but have been looking to finnish writing it recently.

I have recreated the error so it looks like there is an issue introduced with the upgrade from phpBB 3.2 to 3.3.

**Comment by markgawler** [comment]
Typo in migration tool, nothing to do with upgrade from phpBB 3.2 to 3.3.

**Comment by DevoKun** [comment]
I was able to enable the extension! Thank you very much for the fix!

<img width="1279" alt="Screen Shot 2021-11-26 at 5 04 45 PM" src="https://user-images.githubusercontent.com/935976/143658002-db4a119e-3de3-450c-b2d2-19f29b8864ec.png">
